name: Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    uses: QGtiger/.github/.github/workflows/deploy-oss.yml@main
    secrets: inherit
    with:
      APP_NAME: "app-agent-test" # 每个项目只改这里！
